### PR TITLE
Fix Google OAuth login

### PR DESCRIPTION
**Pull request by AlbertoMoricca**
Applied the fixes on Google Oauth login discussed in the topic https://github.com/datamweb/shield-oauth/discussions/25

### CODE REVIEW

**Review by datamweb — APPROVED** [review]
Thank you!

**Comment by AlbertoMoricca** [comment]
Thanks for approval. What's the next step? I need to perform any action?

**Comment by datamweb** [comment]
No, everything is fine. Just wait for it to merge.
This is out of your control.

**Comment by AlbertoMoricca** [comment]
Ok, thanks for clarification!

**Pull request merged**
