### PR TITLE
Fix variable typo

### PR DESCRIPTION
**Pull request by sammyskills**
- [x] Corrected `$this->callbake_url` to `$this->callback_url`.
- [x] Declare vars before usage in method calls.

### CODE REVIEW

**Comment by sammyskills** [comment]
See this:
https://github.com/datamweb/shield-oauth/blob/4da6cdfd7aec4590b0bf9d7e6c880b6508f82763/src/Libraries/GoogleOAuth.php#L62

What class of `Exception` will be called here? 

Asking because my text editor is highlighting it as an error:
`Use of unknown class: 'Datamweb\ShieldOAuth\Libraries\Exception`

**Review by datamweb — DISMISSED** [review]

**Comment by datamweb** [comment]
> What class of `Exception` will be called here?


I intended to fix these problems in #19 , but I lost the energy to do so.
Maybe this is a good warning for me to continue.

You can solve the problem by adding `use Exception;`.

**Comment by sammyskills** [comment]
> You can solve the problem by adding `use Exception;`.

Added to commit.

**Review by datamweb — APPROVED** [review]
Thanks!

**Pull request merged**
